version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    networks:
      - my-net

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    networks:
      - my-net

networks:
  my-net:
