version: '3.9'

services:
  app:
    build: ./src
    container_name: express_app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=appuser
      - DB_PASSWORD=apppass
      - DB_NAME=appdb
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: express_db
    restart: always
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppass
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
